---
title: "LinkedIn_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

wd <- "C:\\Users\\heinr\\OneDrive\\Desktop\\LARGE DATA\\LinkedIn\\Write-up"
knitr::opts_knit$set(root.dir = wd)


library(tidyverse)
library(lmerTest)
```

# Read data
```{r}
df_dist_liwc <- read_csv('../full_files_csv/df_dist_liwc.csv')
df_dist_wemb <- read_csv('../full_files_csv/df_dist_wemb.csv')
df_stay_term <- read_csv('../full_files_csv/df_stay_term.csv')
```

```{r}
df_stay_term$comp_id %>% unique() %>% length()
df_stay_term$person_id %>% unique() %>% length()

df_dist_liwc_clean$comp_id  %>% unique() %>% length()
df_dist_liwc_clean$person_id  %>% unique() %>% length()

df_dist_wemb_clean$comp_id  %>% unique() %>% length()
df_dist_wemb_clean$person_id  %>% unique() %>% length()


length(intersect(df_stay_term$comp_id, df_dist_liwc_clean$comp_id))

length(intersect(df_stay_term$comp_id, df_dist_wemb_clean$comp_id))

length(intersect(df_dist_liwc_clean$comp_id, df_dist_wemb_clean$comp_id))

length(intersect(df_stay_term$person_id, df_dist_liwc_clean$person_id))

length(intersect(df_stay_term$person_id, df_dist_wemb_clean$person_id))

length(intersect(df_dist_liwc_clean$person_id, df_dist_wemb_clean$person_id))

```


# Merge data
```{r}

df_dist_liwc_clean <- df_dist_liwc %>% select(-X, -company, -Filename.x) %>%
  drop_na()

df_dist_wemb_clean <- df_dist_wemb %>% select(-X, -org_profile_link,
                                              -parent_folder, -batch_folder, 
                                              -given_name, -family_name, 
                                              -header_title, -header_location)%>%
  drop_na()


df_dist_liwc_merged <- plyr::join(df_stay_term, df_dist_liwc_clean, 
                                  by=c('comp_id', 'person_id'),
                                  type='inner')

df_dist_wemb_merged <- plyr::join(df_stay_term, df_dist_wemb_clean, 
                                  by=c('comp_id', 'person_id'),
                                  type='inner')


df_dist_liwc_merged_clean <- df_dist_liwc_merged %>% 
  filter(is_current_job == F) %>%
  mutate(n_months = log(n_months)) %>%
  group_by(comp_id) %>%
  mutate_at(vars(n_months, cos_dist, euc_dist, manh_dist, 
                 iforest_ad, ocsvm_ad, sos_ad), scale) %>%
  ungroup()

df_dist_wemb_merged_clean <- df_dist_wemb_merged %>% 
  filter(is_current_job == F) %>%
  mutate(n_months = log(n_months)) %>%
  group_by(comp_id) %>%
  mutate_at(vars(n_months, cos_dist, euc_dist, manh_dist,
                 iforest_ad, ocsvm_ad, sos_ad), scale) %>%
  ungroup()

```



```{r}
run_mlm <- function(data){
  
  mlm_cos_dist <- lmer(n_months ~ cos_dist + (cos_dist|comp_id), 
                     data = data)
  
  mlm_euc_dist <- lmer(n_months ~ euc_dist + (euc_dist|comp_id), 
                     data = data)
  
  mlm_manh_dist <- lmer(n_months ~ manh_dist + (manh_dist|comp_id), 
                     data = data)
  
  mlm_iforest_ad <- lmer(n_months ~ iforest_ad + (iforest_ad|comp_id), 
                     data = data)
  
  mlm_ocsvm_ad <- lmer(n_months ~ ocsvm_ad + (ocsvm_ad|comp_id), 
                     data = data)
  
  mlm_sos_ad <- lmer(n_months ~ sos_ad + (sos_ad|comp_id), 
                     data = data)
  
  
  # create list with results
  results <- list('mlm_cos_dist' = mlm_cos_dist, 
                  "mlm_euc_dist" = mlm_euc_dist,
                  "mlm_manh_dist" = mlm_manh_dist,
                  "mlm_iforest_ad" = mlm_iforest_ad,
                  "mlm_ocsvm_ad" = mlm_ocsvm_ad,
                  "mlm_sos_ad" = mlm_sos_ad)
}
```


```{r}
mlm_aggregator <- function(model_list){

  model_df <- model_list %>%
    map(summary) %>%
    map(coefficients) %>%
    map(as.data.frame) %>%
    map(rownames_to_column, 'pred') %>% 
    bind_rows() %>% 
    filter(str_detect(pred, 'dist|ad'))
  
model_df
  
}

```

# Fit models with LIWC data

```{r}
results_liwc <- run_mlm(df_dist_liwc_merged_clean)
```


```{r}
mlm_aggregator(results_liwc)
```


# Fit models with word embedding data
```{r}
results_wemb <- run_mlm(df_dist_wemb_merged_clean)
```


```{r}
mlm_aggregator(results_wemb)
```

